// frontend-angular/src/app/data/metric-card.component.ts
import { Component, computed, input } from '@angular/core';
import { TooltipComponent } from '../ui/tooltip.component';
import { IconComponent } from '../ui/icon.component';

export interface Stat {
  label: string;
  value: string;
  delta?: string;
  trend?: 'up' | 'down' | 'neutral';
  hint?: string;
}

/** Port of components/data/MetricCard.tsx on its real <div>. */
@Component({
  selector: 'div[ttMetricCard]',
  standalone: true,
  imports: [TooltipComponent, IconComponent],
  host: { class: 'bg-surface border border-line rounded-lg p-4 shadow-[0_2px_10px_rgba(15,23,42,.045)] min-h-[110px]' },
  template: `<div class="flex items-center gap-1.5 text-ink-soft font-semibold text-xs"><span>{{ stat().label }}</span>@if (stat().hint) {<span ttTooltip [label]="stat().hint!"><svg ttIcon="info" class="text-ink-soft/70 hover:text-ink-soft shrink-0"></svg></span>}</div><div class="text-ink font-extrabold text-[26px] tracking-tight mt-2 mb-0.5">{{ stat().value }}</div>@if (stat().delta) {<div [class]="'text-xs font-semibold ' + trendColor()">{{ stat().delta }}</div>}`,
})
export class MetricCardComponent {
  readonly stat = input.required<Stat>();
  readonly trendColor = computed(() => {
    const trend = this.stat().trend ?? 'up';
    return trend === 'up' ? 'text-success' : trend === 'down' ? 'text-danger' : 'text-ink-soft';
  });
}

// frontend/src/components/data/MetricCard.tsx
import { Tooltip } from '../ui/Tooltip';
import { IconInfo } from '../ui/Icons';

interface Props {
  label: string;
  value: string;
  delta?: string;
  trend?: 'up' | 'down' | 'neutral';
  hint?: string;
}

export function MetricCard({ label, value, delta, trend = 'up', hint }: Props) {
  const trendColor = trend === 'up' ? 'text-success-text' : trend === 'down' ? 'text-danger-text' : 'text-ink-soft';
  return (
    <div className="bg-surface border border-line rounded-lg p-4 shadow-[0_2px_10px_rgba(15,23,42,.045)] min-h-[110px]">
      <div className="flex items-center gap-1.5 text-ink-soft font-semibold text-xs">
        <span>{label}</span>
        {hint && (
          <Tooltip label={hint}>
            <IconInfo className="text-ink-soft/70 hover:text-ink-soft shrink-0" />
          </Tooltip>
        )}
      </div>
      <div className="text-ink font-extrabold text-[26px] tracking-tight mt-2 mb-0.5">{value}</div>
      {delta && <div className={`text-xs font-semibold ${trendColor}`}>{delta}</div>}
    </div>
  );
}
