// frontend-angular/src/app/layout/app-layout.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { SidebarComponent } from './sidebar.component';
import { TopBarComponent } from './top-bar.component';
import { ConnectionBannerComponent } from './connection-banner.component';

/** Port of components/Layout/AppLayout.tsx (LiveProvider = the root LiveService). */
@Component({
  selector: 'tt-app-layout',
  standalone: true,
  imports: [RouterOutlet, SidebarComponent, TopBarComponent, ConnectionBannerComponent],
  host: { style: 'display: contents' },
  template: `<div class="flex h-screen bg-canvas"><aside ttSidebar></aside><div class="flex-1 flex flex-col min-w-0"><header ttTopBar></header><tt-connection-banner /><main class="flex-1 overflow-y-auto p-7"><div class="max-w-app mx-auto w-full"><router-outlet /></div></main></div></div>`,
})
export class AppLayoutComponent {}

// frontend/src/components/Layout/AppLayout.tsx
import { Outlet } from 'react-router-dom';
import { Sidebar } from './Sidebar';
import { TopBar } from './TopBar';
import { ConnectionBanner } from './ConnectionBanner';
import { LiveProvider } from '../../context/LiveContext';

export function AppLayout() {
  return (
    <LiveProvider>
      <div className="flex h-screen bg-canvas">
        <Sidebar />
        <div className="flex-1 flex flex-col min-w-0">
          <TopBar />
          <ConnectionBanner />
          <main id="main" tabIndex={-1} className="flex-1 overflow-y-auto p-7 focus:outline-hidden">
            <div className="max-w-app mx-auto w-full">
              <Outlet />
            </div>
          </main>
        </div>
      </div>
    </LiveProvider>
  );
}
