// frontend/src/components/Layout/ConnectionBanner.tsx
import { useEffect, useState } from 'react';
import { useLive } from '../../context/LiveContext';

/**
 * Honest "is this page actually current" indicator. The dashboard has no
 * polling of its own -- pages fetch once and rely on the /ws/live push (see
 * LiveContext) to know when to refetch. If that socket is down, nothing is
 * arriving automatically and the page could be showing stale numbers
 * without the user having any way to tell -- so say so, instead of letting
 * a disconnected "Live" badge imply otherwise.
 */
export function ConnectionBanner() {
  const { connected } = useLive();
  const [graceOver, setGraceOver] = useState(false);

  useEffect(() => {
    if (connected) return;
    // Grace period so a normal page-load reconnect blip doesn't flash a
    // banner every single navigation.
    const t = setTimeout(() => setGraceOver(true), 4000);
    return () => {
      clearTimeout(t);
      setGraceOver(false);
    };
  }, [connected]);

  if (connected || !graceOver) return null;

  return (
    <div
      role="alert"
      className="bg-warning-soft text-warning-text px-7 py-2 text-sm flex items-center justify-between gap-3"
    >
      <span>
        <b>Not connected to the telemetry backend.</b> New data won't load automatically until the connection is back —
        the numbers on screen may be out of date. Check <code className="font-mono">tokentelemetry status</code> if this
        doesn't clear on its own.
      </span>
      <button
        onClick={() => window.location.reload()}
        className="shrink-0 border border-warning rounded-md px-3 py-1 text-xs font-semibold hover:bg-surface"
      >
        Reload
      </button>
    </div>
  );
}

// frontend-angular/src/app/layout/connection-banner.component.ts
import { Component, effect, inject, signal } from '@angular/core';
import { LiveService } from '../lib/live.service';

/** Port of components/Layout/ConnectionBanner.tsx: shown only after 4s disconnected (a reconnect blip never flashes it). */
@Component({
  selector: 'tt-connection-banner',
  standalone: true,
  host: { style: 'display: contents' },
  template: `
    @if (show()) {
      <div class="bg-warning-soft text-warning px-7 py-2 text-sm flex items-center justify-between gap-3">
        <span><b>Not connected to the telemetry backend.</b> New data won't load automatically until the connection is back — the numbers on screen may be out of date. Check <code class="font-mono">tokentelemetry status</code><ng-container>{{ ' ' }}</ng-container>if this doesn't clear on its own.</span>
        <button (click)="reload()" class="shrink-0 border border-warning rounded-md px-3 py-1 text-xs font-semibold hover:bg-surface">Reload</button>
      </div>
    }
  `,
})
export class ConnectionBannerComponent {
  private readonly live = inject(LiveService);
  readonly show = signal(false);
  reload = () => window.location.reload();

  constructor() {
    effect((onCleanup) => {
      if (this.live.connected()) {
        this.show.set(false);
        return;
      }
      const t = setTimeout(() => this.show.set(true), 4000);
      onCleanup(() => clearTimeout(t));
    }, { allowSignalWrites: true });
  }
}
