// frontend/src/pages/ProjectsList.tsx
import { useMemo, useState } from 'react';
import { useApi } from '../hooks/useApi';
import { useLive } from '../context/LiveContext';
import { getProjects } from '../api/projects';
import { ProjectCard } from '../components/cards/ProjectCard';
import { Button } from '../components/ui/Button';
import { IconRefresh } from '../components/ui/Icons';
import { PageHead, ErrorPanel } from './GlobalDashboard';

export function ProjectsList() {
  const { version: liveVersion } = useLive();
  const { data: projects = [], loading, error, reload } = useApi((signal) => getProjects(signal), [liveVersion]);
  const [q, setQ] = useState('');

  const filtered = useMemo(
    () => projects.filter((p) => p.project.toLowerCase().includes(q.toLowerCase())),
    [projects, q],
  );

  if (error) return <ErrorPanel message={error.message} />;
  if (loading && projects.length === 0) return <div className="p-10 text-center text-ink-soft">Loading projects…</div>;

  return (
    <div className="space-y-6">
      <PageHead
        eyebrow="Inventory"
        title="Projects"
        subtitle="Every project is an independent telemetry scope with its own sessions, requests, tools and skills."
        actions={
          <Button onClick={reload} className="flex items-center gap-1.5">
            <IconRefresh width={14} height={14} /> Discover projects
          </Button>
        }
      />
      <input
        value={q}
        onChange={(e) => setQ(e.target.value)}
        placeholder="Search projects…"
        className="h-10 border border-line bg-surface rounded-md px-3 text-sm w-full max-w-sm outline-none focus:border-accent focus:ring-4 focus:ring-accent-soft"
      />
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {filtered.length === 0 ? (
          <div className="col-span-full p-10 text-center text-ink-soft bg-surface border border-line rounded-lg">
            No projects match.
          </div>
        ) : (
          filtered.map((p) => <ProjectCard key={p.project} p={p} />)
        )}
      </div>
    </div>
  );
}

// frontend-angular/src/app/pages/projects-list.component.ts
import { Component, computed, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ApiResource } from '../lib/api-resource';
import { LiveService } from '../lib/live.service';
import { getProjects } from '../api/projects';
import { PageHeadComponent, ErrorPanelComponent } from './page-head.component';
import { ButtonComponent } from '../ui/button.component';
import { IconComponent } from '../ui/icon.component';
import { ProjectCardComponent } from './project-card.component';

/** Port of pages/ProjectsList.tsx. */
@Component({
  selector: 'tt-projects-list',
  standalone: true,
  imports: [RouterLink, PageHeadComponent, ErrorPanelComponent, ButtonComponent, IconComponent, ProjectCardComponent],
  host: { style: 'display: contents' },
  template: `
    @if (res.error(); as err) {
      <div ttErrorPanel [message]="err.message"></div>
    } @else if (res.loading() && projects().length === 0) {
      <div class="p-10 text-center text-ink-soft">Loading projects…</div>
    } @else {
      <div class="space-y-6">
        <div ttPageHead eyebrow="Inventory" title="Projects" subtitle="Every project is an independent telemetry scope with its own sessions, requests, tools and skills." [hasActions]="true"><button ttButton (click)="res.reload()" class="flex items-center gap-1.5"><svg ttIcon="refresh" [width]="14" [height]="14"></svg> Discover projects</button></div>
        <input [value]="q()" (input)="q.set($any($event.target).value)" placeholder="Search projects…" class="h-10 border border-line bg-surface rounded-md px-3 text-sm w-full max-w-sm outline-none focus:border-accent focus:ring-4 focus:ring-accent-soft" />
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          @if (filtered().length === 0) {
            <div class="col-span-full p-10 text-center text-ink-soft bg-surface border border-line rounded-lg">No projects match.</div>
          } @else {
            @for (p of filtered(); track p.project) {<a ttProjectCard [p]="p" [routerLink]="'/projects/' + enc(p.project)"></a>}
          }
        </div>
      </div>
    }
  `,
})
export class ProjectsListComponent {
  private readonly live = inject(LiveService);
  readonly res = new ApiResource(() => getProjects(), () => [this.live.version()]);
  readonly projects = computed(() => this.res.data() ?? []);
  readonly q = signal('');
  readonly filtered = computed(() => this.projects().filter((p) => p.project.toLowerCase().includes(this.q().toLowerCase())));
  enc = encodeURIComponent;
}
