// frontend/src/pages/Settings.tsx
import { useApi } from '../hooks/useApi';
import { getSettings, triggerReconcile } from '../api/settings';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';
import { fmt } from '../lib/format';
import { PageHead, ErrorPanel } from './GlobalDashboard';

export function Settings() {
  const { data: s, loading, error, reload } = useApi((signal) => getSettings(signal), []);
  if (error) return <ErrorPanel message={error.message} />;
  if (loading || !s) return <div className="p-10 text-center text-ink-soft">Loading settings…</div>;

  const handleReconcile = async () => {
    await triggerReconcile();
    reload();
  };

  return (
    <div className="space-y-6">
      <PageHead
        eyebrow="Operations"
        title="Telemetry settings"
        subtitle="Local-first collector configuration compatible with the Claude Token Telemetry v5 architecture."
        actions={
          <Button variant="primary" onClick={handleReconcile}>
            Reconcile now
          </Button>
        }
      />
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-surface border border-line rounded-lg p-4">
          <div className="font-bold text-sm mb-3">Collector</div>
          <KV k="Version" v={s.version ? `v${s.version} · schema v${s.schema_version}` : '—'} />
          <KV k="Database" v={<span className="font-mono text-xs">{s.db_path}</span>} />
          <KV k="DB size" v={`${fmt(s.db_size)} bytes`} />
          <KV k="Poll interval" v={`${s.env.CLAUDE_TELEMETRY_INTERVAL || '5'} seconds`} />
          <KV k="Last reconcile" v={s.last_reconcile || '—'} />
        </div>
        <div className="bg-surface border border-line rounded-lg p-4">
          <div className="font-bold text-sm mb-3">Data semantics</div>
          <KV k="Request usage" v={<Badge tone="success">Exact</Badge>} />
          <KV k="Tool/path attribution" v={<Badge tone="warning">Estimated</Badge>} />
          <KV k="Skills" v={<Badge tone="info">Tracked</Badge>} />
        </div>
      </div>
      {s.exporters && (
        <div className="bg-surface border border-line rounded-lg p-4">
          <div className="font-bold text-sm mb-3">Integrations</div>
          {s.exporters.map((e) => (
            <KV
              key={e.name}
              k={e.name === 'otlp' ? 'OpenTelemetry (OTLP)' : 'Webhook'}
              v={
                e.enabled ? (
                  <span className="flex flex-wrap items-center gap-2">
                    <Badge tone="success">On</Badge>
                    <span className="font-mono text-xs break-all">{e.target}</span>
                    <span className="text-ink-soft text-xs">{fmt(e.pending_rows)} rows pending</span>
                  </span>
                ) : (
                  <span className="text-ink-soft text-xs">
                    Off — set {e.name === 'otlp' ? 'TOKENTELEMETRY_OTLP_ENDPOINT' : 'TOKENTELEMETRY_WEBHOOK_URL'} to
                    enable
                  </span>
                )
              }
            />
          ))}
        </div>
      )}
      <div className="bg-surface border border-line rounded-lg p-4">
        <div className="font-bold text-sm mb-3">Table counts</div>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
          {Object.entries(s.table_counts).map(([k, v]) => (
            <div key={k} className="bg-surface-muted rounded-lg p-3.5">
              <div className="text-ink-soft text-[11px]">{k}</div>
              <div className="font-extrabold text-lg">{fmt(v)}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function KV({ k, v }: { k: string; v: React.ReactNode }) {
  return (
    <div className="grid grid-cols-[150px_1fr] gap-2 py-1.5 border-b border-line last:border-0 text-sm">
      <span className="text-ink-soft">{k}</span>
      <span>{v}</span>
    </div>
  );
}

// frontend-angular/src/app/pages/settings.component.ts
import { Component, computed } from '@angular/core';
import { ApiResource } from '../lib/api-resource';
import { getSettings, triggerReconcile } from '../api/settings';
import { fmt } from '../lib/format';
import { PageHeadComponent, ErrorPanelComponent } from './page-head.component';
import { BadgeComponent } from '../ui/badge.component';
import { ButtonComponent } from '../ui/button.component';

/** Port of pages/Settings.tsx. */
@Component({
  selector: 'tt-settings',
  standalone: true,
  imports: [PageHeadComponent, ErrorPanelComponent, BadgeComponent, ButtonComponent],
  host: { style: 'display: contents' },
  template: `
    @if (res.error(); as err) {
      <div ttErrorPanel [message]="err.message"></div>
    } @else if (res.loading() || !res.data()) {
      <div class="p-10 text-center text-ink-soft">Loading settings…</div>
    } @else {
      <div class="space-y-6">
        <div ttPageHead eyebrow="Operations" title="Telemetry settings" subtitle="Local-first collector configuration compatible with the Claude Token Telemetry v5 architecture." [hasActions]="true"><button ttButton variant="primary" (click)="reconcile()">Reconcile now</button></div>
        <div class="grid grid-cols-2 gap-4">
          <div class="bg-surface border border-line rounded-lg p-4">
            <div class="font-bold text-sm mb-3">Collector</div>
            <div class="grid grid-cols-[150px_1fr] gap-2 py-1.5 border-b border-line last:border-0 text-sm"><span class="text-ink-soft">Database</span><span><span class="font-mono text-xs">{{ s().db_path }}</span></span></div>
            <div class="grid grid-cols-[150px_1fr] gap-2 py-1.5 border-b border-line last:border-0 text-sm"><span class="text-ink-soft">DB size</span><span>{{ fmt(s().db_size) + ' bytes' }}</span></div>
            <div class="grid grid-cols-[150px_1fr] gap-2 py-1.5 border-b border-line last:border-0 text-sm"><span class="text-ink-soft">Poll interval</span><span>{{ (s().env['CLAUDE_TELEMETRY_INTERVAL'] || '5') + ' seconds' }}</span></div>
            <div class="grid grid-cols-[150px_1fr] gap-2 py-1.5 border-b border-line last:border-0 text-sm"><span class="text-ink-soft">Last reconcile</span><span>{{ s().last_reconcile || '—' }}</span></div>
          </div>
          <div class="bg-surface border border-line rounded-lg p-4">
            <div class="font-bold text-sm mb-3">Data semantics</div>
            <div class="grid grid-cols-[150px_1fr] gap-2 py-1.5 border-b border-line last:border-0 text-sm"><span class="text-ink-soft">Request usage</span><span><span ttBadge tone="success">Exact</span></span></div>
            <div class="grid grid-cols-[150px_1fr] gap-2 py-1.5 border-b border-line last:border-0 text-sm"><span class="text-ink-soft">Tool/path attribution</span><span><span ttBadge tone="warning">Estimated</span></span></div>
            <div class="grid grid-cols-[150px_1fr] gap-2 py-1.5 border-b border-line last:border-0 text-sm"><span class="text-ink-soft">Skills</span><span><span ttBadge tone="info">Tracked</span></span></div>
          </div>
        </div>
        <div class="bg-surface border border-line rounded-lg p-4">
          <div class="font-bold text-sm mb-3">Table counts</div>
          <div class="grid grid-cols-3 gap-3">
            @for (e of counts(); track e[0]) {<div class="bg-surface-muted rounded-lg p-3.5"><div class="text-ink-soft text-[11px]">{{ e[0] }}</div><div class="font-extrabold text-lg">{{ fmt(e[1]) }}</div></div>}
          </div>
        </div>
      </div>
    }
  `,
})
export class SettingsComponent {
  readonly res = new ApiResource(() => getSettings());
  readonly s = computed(() => this.res.data()!);
  readonly counts = computed(() => Object.entries(this.res.data()?.table_counts ?? {}));
  fmt = fmt;
  async reconcile() {
    await triggerReconcile();
    this.res.reload();
  }
}
